### ISSUE TITLE
Application crashes during benchmark when iperf3 is being used

### ISSUE THREAD

**Issue by marvn23** [Nischay-Pro/wifi-heat-mapper#5]
Application will crash with following trace:

Running benchmark
  0%|                                                                                                                                 | 0/15 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/whm", line 33, in <module>
    sys.exit(load_entry_point('whm==0.2.2', 'console_scripts', 'whm')())
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/main.py", line 72, in driver
    start_gui(args.floor_map, args.iperf_server, args.config_file)
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/gui.py", line 190, in start_gui
    results = run_benchmarks(benchmark_modes, benchmark_iterations, iperf_ip, iperf_port,
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/gui.py", line 437, in run_benchmarks
    iperf_download = run_iperf(iperf_ip, iperf_port, bind_address, download=True, protocol="tcp")
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 246, in run_iperf
    run_iperf(ip, port, bind_address, download, protocol, retry + 1)
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 246, in run_iperf
    run_iperf(ip, port, bind_address, download, protocol, retry + 1)
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 244, in run_iperf
    raise err
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 240, in run_iperf
    get_property_from(iperf_result_json, "start")
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 403, in get_property_from
    raise ValueError("Could not retrieve property {0}".format(key)) from None
ValueError: Could not retrieve property start

$ iperf3 --version
iperf 3.9 (cJSON 1.7.13)
Linux fedora 5.11.20-300.fc34.x86_64 #1 SMP Wed May 12 12:45:10 UTC 2021 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication

Application won't crash if only graphs 1 2 3 are selected.

**Comment by Nischay-Pro** [comment]
In a terminal on your client PC can you run this command

`iperf3 -c 192.168.1.1 -p 5201 --json `

Replace 192.168.1.1 with your server IP and 5201 with your server port on which iperf3 is running.

**Comment by Nischay-Pro** [comment]
It seems your iperf3 is working as expected. Just to help me reproduce on my Fedora instance can you share me your configuration file which you bootstrapped.

**Comment by marvn23** [comment]
Uploading as .txt as github doesn't allow .json
[config_all.txt](https://github.com/Nischay-Pro/wifi-heat-mapper/files/6501842/config_all.txt)

**Comment by Nischay-Pro** [comment]
Found another bug while debugging your problem. It looks like when you selected 'all' graphs the tool tried to benchmark graphs for which the backends were missing in your system. I will push an update which patches this issue.

In the meantime can you try this configuration.
[config_all.txt](https://github.com/Nischay-Pro/wifi-heat-mapper/files/6502060/config_all.txt)

Just to confirm can you tell me if you are passing the `--server` or `-s` flag while running `whm benchmark`.

**Comment by marvn23** [comment]
Just tried it with the cofiguration you've posted (and with disabled selinux), but still the same result:

$ whm benchmark -m C2W.png -s 10.0.11.57 -c config2.json
Loaded configuration file from: /home/marvn/whm/config2.json
Target Interface: wlp2s0 and SSID: XXXXXX
Loading floor map
Loaded floor map
Ready for benchmarking.
Running benchmark
  0%|                                                                                                                                 | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/whm", line 33, in <module>
    sys.exit(load_entry_point('whm==0.2.2', 'console_scripts', 'whm')())
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/main.py", line 72, in driver
    start_gui(args.floor_map, args.iperf_server, args.config_file)
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/gui.py", line 190, in start_gui
    results = run_benchmarks(benchmark_modes, benchmark_iterations, iperf_ip, iperf_port,
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/gui.py", line 437, in run_benchmarks
    iperf_download = run_iperf(iperf_ip, iperf_port, bind_address, download=True, protocol="tcp")
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 246, in run_iperf
    run_iperf(ip, port, bind_address, download, protocol, retry + 1)
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 246, in run_iperf
    run_iperf(ip, port, bind_address, download, protocol, retry + 1)
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 244, in run_iperf
    raise err
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 240, in run_iperf
    get_property_from(iperf_result_json, "start")
  File "/usr/local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 403, in get_property_from
    raise ValueError("Could not retrieve property {0}".format(key)) from None
ValueError: Could not retrieve property start

On the server side, there are 3 finished benchmarks before the client crashes. Each of these benchmarks ends with
iperf3: error - select failed: Bad file descriptor

iperf3 is runnig with just $iperf3 -s on the server

**Comment by Nischay-Pro** [comment]
I pushed some changes which fixed some bugs. Can you try rerunning bootstrap command regenerating the config.json file and let me know if any problem occurs.

The new update should tell the exact problem we are facing now.

**Comment by marvn23** [comment]
OK, after upgrade and rebootstraping, the trace have more information:

$ whm benchmark -m C2W.png -s 10.0.11.57 -c config_all.json 
Loaded configuration file from: /home/marvn/whm/config_all.json
Target Interface: wlp2s0 and SSID: 2N-Private
Loading floor map
Loaded floor map
Ready for benchmarking.
Running benchmark
  0%|                                                                                                                                  | 0/4 [00:00<?, ?it/s]ERROR:root:Output from iperf3 : {'error': 'unable to receive results: '}
ERROR:root:Unable to parse iperf3 result
Traceback (most recent call last):
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 248, in run_iperf
    get_property_from(iperf_result_json, "end")
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 420, in get_property_from
    raise ValueError("Could not retrieve property {0}".format(key)) from None
ValueError: Could not retrieve property end
WARNING:root:Rerunning iperf3 with retry count 1
ERROR:root:Output from iperf3 : {'error': 'unable to receive results: '}
ERROR:root:Unable to parse iperf3 result
Traceback (most recent call last):
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 248, in run_iperf
    get_property_from(iperf_result_json, "end")
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 420, in get_property_from
    raise ValueError("Could not retrieve property {0}".format(key)) from None
ValueError: Could not retrieve property end
WARNING:root:Rerunning iperf3 with retry count 2
ERROR:root:Output from iperf3 : {'error': 'unable to receive results: '}
ERROR:root:Unable to parse iperf3 result
Traceback (most recent call last):
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 248, in run_iperf
    get_property_from(iperf_result_json, "end")
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 420, in get_property_from
    raise ValueError("Could not retrieve property {0}".format(key)) from None
ValueError: Could not retrieve property end
Traceback (most recent call last):
  File "/usr/local/bin/whm", line 8, in <module>
    sys.exit(driver())
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/main.py", line 84, in driver
    start_gui(args.floor_map, args.iperf_server, args.config_file)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/debugger.py", line 12, in new_func
    return func(*args, **kwargs)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/gui.py", line 213, in start_gui
    results = run_benchmarks(benchmark_modes, benchmark_iterations, iperf_ip, iperf_port,
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/gui.py", line 466, in run_benchmarks
    iperf_download = run_iperf(iperf_ip, iperf_port, bind_address, download=True, protocol="tcp")
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/debugger.py", line 12, in new_func
    return func(*args, **kwargs)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 257, in run_iperf
    run_iperf(ip, port, bind_address, download, protocol, retry + 1)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/debugger.py", line 12, in new_func
    return func(*args, **kwargs)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 257, in run_iperf
    run_iperf(ip, port, bind_address, download, protocol, retry + 1)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/debugger.py", line 12, in new_func
    return func(*args, **kwargs)
  File "/home/marvn/.local/lib/python3.9/site-packages/wifi_heat_mapper/misc.py", line 253, in run_iperf
    raise ExternalError("External Error generated from iperf3: {0}".format(iperf_result_json["error"])) from\
wifi_heat_mapper.misc.ExternalError: External Error generated from iperf3: unable to receive results: 
  0%|

**Comment by Nischay-Pro** [comment]
It looks like for some reason iperf3 is not able to capture results. 

An issue posted on iperf3 suggests to me that iperf3 cannot bind properly to your wlan interface.
https://github.com/esnet/iperf/issues/521

Can you try running benchmark with the `--debug` flag and share me the `debug.log` file generated in the folder?

**Comment by marvn23** [comment]
One more thing I've found is that if I run the iperf manually from python (like the example [here](https://iperf3-python.readthedocs.io/en/latest/examples.html)), it works for the first time, but it fails on every other run.  The issue is described here: https://github.com/thiezn/iperf3-python/issues/37

This might be a reason why it's not able to capture results.

**Comment by marvn23** [comment]
[debug.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/6507518/debug.log)

Here is the debug log from running $whm benchmark -m C2W.png -s 10.0.11.57 -c config_all.json --debug

**Comment by marvn23** [comment]
I've tried to run the debug when connecter remotelly via ssh -X and that way, it can retrieve results from the server. But it will then fail to parse them. I'm attaching the debug from the "remote" run.
[debug_remote.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/6507937/debug_remote.log)

(I have no idea why it works from ssh and not locally. I might try different terminal emulator, but never seen this behaviour before)

**Comment by Nischay-Pro** [comment]
Yeah. This property should be start and not error.

Can you try running iperf3 with these commands?
iperf3 -c 10.0.11.61 -p 5201 -B wlp2s0

This is basically what should be running.

**Comment by Nischay-Pro** [comment]
In your python interpreter could you try running the equivalent iperf3 code. I'm unsure why it stops working after sometime and I have some trouble reproducing it my side. I'm trying to reproduce it on Fedora 34 Client and Fedora 34 Server with latest updates but I'm unable to do so.

```python
import iperf3

client = iperf3.Client()
client.server_hostname = "10.0.11.57"
client.port = 5201
client.bind_address = "10.0.11.61"
client.reverse = False
client.verbose = False
client.protocol = "tcp"
iperf_result = client.run()
print(iperf_result.json)
```

**Comment by marvn23** [comment]
When I run it from python interpreter, it works both locally and from ssh. But the whm is failing locally for some reason. 

Python 3.9.5 (default, May  4 2021, 00:00:00) 
[GCC 11.1.1 20210428 (Red Hat 11.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iperf3
>>> 
>>> client = iperf3.Client()
>>> client.server_hostname = "10.0.11.57"
>>> client.port = 5201
>>> client.bind_address = "10.0.11.61"
>>> client.reverse = False
>>> client.verbose = False
>>> client.protocol = "tcp"
>>> iperf_result = client.run()
>>> print(iperf_result.json)
{'start': {'connected': [{'socket': 9, 'local_host': '10.0.11.61', 'local_port': 56625, 'remote_host': '10.0.11.57', 'remote_port': 5201}], 'version': 'iperf 3.9', 'system_info': 'Linux fedora 5.11.20-300.fc34.x86_64 #1 SMP Wed May 12 12:45:10 UTC 2021 x86_64', 'timestamp': {'time': 'Wed, 19 May 2021 12:18:04 GMT', 'timesecs': 1621426684}, 'connecting_to': {'host': '10.0.11.57', 'port': 5201}, 'cookie': '3cogugez7tefngehv72vnklwc6z5ycclua54', 'tcp_mss_default': 1448, 'sock_bufsize': 0, 'sndbuf_actual': 16384, 'rcvbuf_actual': 131072, 'test_start': {'protocol': 'TCP', 'num_streams': 1, 'blksize': 131072, 'omit': 0, 'duration': 10, 'bytes': 0, 'blocks': 0, 'reverse': 0, 'tos': 0}}, 'intervals': [{'streams': [{'socket': 9, 'start': 0, 'end': 1.000152, 'seconds': 1.0001519918441772, 'bytes': 21168496, 'bits_per_second': 169322232.40163708, 'retransmits': 0, 'snd_cwnd': 876040, 'rtt': 24961, 'rttvar': 1760, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 0, 'end': 1.000152, 'seconds': 1.0001519918441772, 'bytes': 21168496, 'bits_per_second': 169322232.40163708, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 1.000152, 'end': 2.000369, 'seconds': 1.0002169609069824, 'bytes': 18350080, 'bits_per_second': 146768796.908706, 'retransmits': 0, 'snd_cwnd': 931064, 'rtt': 23474, 'rttvar': 3754, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 1.000152, 'end': 2.000369, 'seconds': 1.0002169609069824, 'bytes': 18350080, 'bits_per_second': 146768796.908706, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 2.000369, 'end': 3.000111, 'seconds': 0.9997419714927673, 'bytes': 19660800, 'bits_per_second': 157326994.84962845, 'retransmits': 0, 'snd_cwnd': 1029528, 'rtt': 33914, 'rttvar': 5300, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 2.000369, 'end': 3.000111, 'seconds': 0.9997419714927673, 'bytes': 19660800, 'bits_per_second': 157326994.84962845, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 3.000111, 'end': 4.000188, 'seconds': 1.00007700920105, 'bytes': 19660800, 'bits_per_second': 157274288.43270212, 'retransmits': 0, 'snd_cwnd': 1029528, 'rtt': 24701, 'rttvar': 1517, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 3.000111, 'end': 4.000188, 'seconds': 1.00007700920105, 'bytes': 19660800, 'bits_per_second': 157274288.43270212, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 4.000188, 'end': 5.000187, 'seconds': 0.9999989867210388, 'bytes': 19660800, 'bits_per_second': 157286559.3751615, 'retransmits': 0, 'snd_cwnd': 1099032, 'rtt': 20586, 'rttvar': 880, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 4.000188, 'end': 5.000187, 'seconds': 0.9999989867210388, 'bytes': 19660800, 'bits_per_second': 157286559.3751615, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 5.000187, 'end': 6.000147, 'seconds': 0.9999600052833557, 'bytes': 19660800, 'bits_per_second': 157292690.87660182, 'retransmits': 0, 'snd_cwnd': 1210528, 'rtt': 18855, 'rttvar': 1566, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 5.000187, 'end': 6.000147, 'seconds': 0.9999600052833557, 'bytes': 19660800, 'bits_per_second': 157292690.87660182, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 6.000147, 'end': 7.000236, 'seconds': 1.0000890493392944, 'bytes': 19660800, 'bits_per_second': 157272394.99713627, 'retransmits': 0, 'snd_cwnd': 1274240, 'rtt': 19610, 'rttvar': 1274, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 6.000147, 'end': 7.000236, 'seconds': 1.0000890493392944, 'bytes': 19660800, 'bits_per_second': 157272394.99713627, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 7.000236, 'end': 8.000218, 'seconds': 0.9999819993972778, 'bytes': 18350080, 'bits_per_second': 146803282.54756746, 'retransmits': 0, 'snd_cwnd': 1339400, 'rtt': 30724, 'rttvar': 2980, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 7.000236, 'end': 8.000218, 'seconds': 0.9999819993972778, 'bytes': 18350080, 'bits_per_second': 146803282.54756746, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 8.000218, 'end': 9.000188, 'seconds': 0.999970018863678, 'bytes': 18350080, 'bits_per_second': 146805041.38195843, 'retransmits': 0, 'snd_cwnd': 1339400, 'rtt': 22894, 'rttvar': 1809, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 8.000218, 'end': 9.000188, 'seconds': 0.999970018863678, 'bytes': 18350080, 'bits_per_second': 146805041.38195843, 'retransmits': 0, 'omitted': False, 'sender': True}}, {'streams': [{'socket': 9, 'start': 9.000188, 'end': 10.000218, 'seconds': 1.0000300407409668, 'bytes': 17039360, 'bits_per_second': 136310785.12301314, 'retransmits': 0, 'snd_cwnd': 1339400, 'rtt': 31592, 'rttvar': 4237, 'pmtu': 1500, 'omitted': False, 'sender': True}], 'sum': {'start': 9.000188, 'end': 10.000218, 'seconds': 1.0000300407409668, 'bytes': 17039360, 'bits_per_second': 136310785.12301314, 'retransmits': 0, 'omitted': False, 'sender': True}}], 'end': {'streams': [{'sender': {'socket': 9, 'start': 0, 'end': 10.000218, 'seconds': 10.000218, 'bytes': 191562096, 'bits_per_second': 153246336.02987453, 'retransmits': 0, 'max_snd_cwnd': 1339400, 'max_rtt': 33914, 'min_rtt': 18855, 'mean_rtt': 25131, 'sender': True}, 'receiver': {'socket': 9, 'start': 0, 'end': 10.014841, 'seconds': 10.000218, 'bytes': 189249256, 'bits_per_second': 151175045.9143585, 'sender': True}}], 'sum_sent': {'start': 0, 'end': 10.000218, 'seconds': 10.000218, 'bytes': 191562096, 'bits_per_second': 153246336.02987453, 'retransmits': 0, 'sender': True}, 'sum_received': {'start': 0, 'end': 10.014841, 'seconds': 10.014841, 'bytes': 189249256, 'bits_per_second': 151175045.9143585, 'sender': True}, 'cpu_utilization_percent': {'host_total': 0.772941126013491, 'host_user': 0.1553761773151579, 'host_system': 0.6176048450078246, 'remote_total': 0.6221271110043125, 'remote_user': 0.006429746705090659, 'remote_system': 0.6156872889583416}, 'sender_tcp_congestion': 'cubic', 'receiver_tcp_congestion': 'cubic'}}

Another wierd thing - running $iperf3 -c 10.0.11.61 -p 5201 -B wlp2s0 doesn't work and ends with 
iperf3: error - unable to send control message: Bad file descriptor

but when I run it without specifing the ifce - $iperf3 -c 10.0.11.61 -p 5201 , it wokrs just fine. And there is only one active ifce on the notebook, ethernet cable is not connected.

It seems to me we are debugging iperf3 and not whm here...

**Comment by Nischay-Pro** [comment]
I think binding to an interface is buggy in iperf3. If it is possible can you try a local build of whm with this property commented out. See if the benchmarking works on your machine.

https://github.com/Nischay-Pro/wifi-heat-mapper/blob/fcb7788481ac14bde9d641a5a7bd42dd872551bf/wifi_heat_mapper/misc.py#L236

**Comment by marvn23** [comment]
I've just tried that, but it didn't help. I can try from another laptop. The one I'm using is old latitude. I can try a modern one, but old laptops usually work better than the new one.
I've also try to trace it with wireshark and at the end of each benchmark, there are a lot of malformed and RST packets - so it seems this is some lower level issue. There are no RST packets when running from interpreter or remotely, which is strange.

**Comment by Nischay-Pro** [comment]
My only suggestion is you should submit a bug report on the official iperf3 repo. They would have a better picture as to why it is failing.

**Comment by marvn23** [comment]
I've just tried it from modern laptop and it works fine. There is still an error with UDP, but that's on iperf3 too. Thanks for your help, I believe this issue can be closed now.
