### ISSUE TITLE
Unable to parse IW

### ISSUE THREAD

**Issue by eclc1924** [Nischay-Pro/wifi-heat-mapper#6]
Hello I am trying to run it on a raspberry pi 400 running ubuntu desktop 64bit. I get this error where it's not detecting wlan0 but wlan0 is up.

whm bootstrap
Detecting benchmarking capabilities.
Supported Modes: iperf3
Please enter the target wireless interface to run benchmark on (example: wlan0): wlan0
Traceback (most recent call last):
  File "/usr/local/bin/whm", line 8, in <module>
    sys.exit(driver())
  File "/usr/local/lib/python3.9/dist-packages/wifi_heat_mapper/main.py", line 81, in driver
    start_config(args.config_file)
  File "/usr/local/lib/python3.9/dist-packages/wifi_heat_mapper/debugger.py", line 12, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/wifi_heat_mapper/config.py", line 228, in start_config
    ssid = process_iw(target_interface)["ssid"]
  File "/usr/local/lib/python3.9/dist-packages/wifi_heat_mapper/misc.py", line 186, in process_iw
    raise ParseError("Unable to parse iw.") from None
wifi_heat_mapper.misc.ParseError: Unable to parse iw.

**Comment by Nischay-Pro** [comment]
Hey. Can you share me the version of iw and the output from the following command?

`iw wlan0 info`

**Comment by eclc1924** [comment]
Interface wlan0
	ifindex 2
	wdev 0x1
	addr e4:5f:01:7f:b5:b1
	ssid watermelon
	type managed
	wiphy 0
	channel 6 (2437 MHz), width: 20 MHz, center1: 2437 MHz
	txpower 31.00 dBm

**Comment by eclc1924** [comment]
iw version is 5.9
[info.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/8517355/info.log)

[station.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/8517354/station.log)

**Comment by Nischay-Pro** [comment]
It looks like the regex for capturing signal strength from `iw` is not working. In your case the signal strength is not available from iw.

Can you run this command and share the log file generated.

`iwconfig wlan0 > iwconfig.log`

**Comment by eclc1924** [comment]
Thanks. I'll try reinstalling iw.
[iwconfig.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/8535420/iwconfig.log)

**Comment by Nischay-Pro** [comment]
@eclc1924 Can you clone the repo and try it now building it from source? It should work now.

**Comment by lordgosub** [comment]
Hello!
Similar problem here.
Arch Linux, lenovo yoga 720 laptop.
[wifi-heat-mapper ](https://aur.archlinux.org/packages/wifi-heat-mapper)package

$whm bootstrap
Detecting benchmarking capabilities.
Supported Modes: iperf3
Please enter the target wireless interface to run benchmark on (example: wlan0): wlan0
Traceback (most recent call last):
  File "/usr/bin/whm", line 8, in <module>
    sys.exit(driver())
  File "/usr/lib/python3.10/site-packages/wifi_heat_mapper/main.py", line 81, in driver
    start_config(args.config_file)
  File "/usr/lib/python3.10/site-packages/wifi_heat_mapper/debugger.py", line 12, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/wifi_heat_mapper/config.py", line 228, in start_config
    ssid = process_iw(target_interface)["ssid"]
  File "/usr/lib/python3.10/site-packages/wifi_heat_mapper/misc.py", line 197, in process_iw
    raise ParseError("Unable to parse iw.") from None
wifi_heat_mapper.misc.ParseError: Unable to parse iw.

Some info:
[iwconfig.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/9865563/iwconfig.log)
[iwversion.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/9865564/iwversion.log)
[station.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/9865565/station.log)
[info.log](https://github.com/Nischay-Pro/wifi-heat-mapper/files/9865566/info.log)

Kind regards to your amazing work!

**Comment by bhuvanchandra** [comment]
I too am facing the same issue, I tried both the pip version and also the version from the source.

 whm bootstrap
Detecting benchmarking capabilities.
Supported Modes: iperf3 speedtest
Please enter the target wireless interface to run benchmark on (example: wlan0): wlp0s20f3
Traceback (most recent call last):
  File "/usr/bin/whm", line 33, in <module>
    sys.exit(load_entry_point('whm==0.2.5', 'console_scripts', 'whm')())
  File "/usr/lib/python3.10/site-packages/whm-0.2.5-py3.10.egg/wifi_heat_mapper/main.py", line 81, in driver
  File "/usr/lib/python3.10/site-packages/whm-0.2.5-py3.10.egg/wifi_heat_mapper/debugger.py", line 12, in new_func
  File "/usr/lib/python3.10/site-packages/whm-0.2.5-py3.10.egg/wifi_heat_mapper/config.py", line 228, in start_config
  File "/usr/lib/python3.10/site-packages/whm-0.2.5-py3.10.egg/wifi_heat_mapper/misc.py", line 197, in process_iw
wifi_heat_mapper.misc.ParseError: Unable to parse iw.

**Comment by Nischay-Pro** [comment]
Probably cause I am parsing from IW. Need to find a better way to parse WiFi data instead of using a hack.

**Comment by cybersholt** [comment]
@Nischay-Pro could you let us know what version specifically we need for this to be able to parse correctly?

Same issue for me with:
**Host info**
```
Operating System: Pop!_OS 22.04 LTS x86_64
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3806MiB
```

**IW Info**
```iw version 5.16```
**Interface Info**
```iw wlp2s0 info
Interface wlp2s0
	ifindex 3
	wdev 0x1
	addr b4:6d:83:04:37:7e
	type managed
	wiphy 0
	channel 157 (5785 MHz), width: 80 MHz, center1: 5775 MHz
	txpower 22.00 dBm
	multicast TXQ:
		qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
		0	0	0	0	0	0	0	00
```

**Comment by sixtyfive** [comment]
Same here ... iw changing output too much?

**Comment by RDKRACZ** [comment]
same for me

**Comment by fedecupe** [comment]
Hi, I'm facing the same issue. Any solution?

**Comment by DominikBobinski** [comment]
Same issue here. I have a dirty workaround that worked for me.
In misc.py, line 183 we're trying to find "ssid" from iw info. For some networks it shows up, for others it does not. I didn't go into why that is. When it doesn't appear we get the parsing error.

My easy "fix" is replacing 

`results["ssid"] = re.findall(r"(?<=ssid )(.*)", iw_info)[0]`
 
 with
 
`results["ssid"] = "fake ssid"`
