### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by balucio** [Nischay-Pro/wifi-heat-mapper#7]
Hi, I tried your program.
I used a floorplan image created with inkscape and then I exported it in png. 

When i start the benchmarking the size of canvas does not fit in screen, the image is only a part of the canvas.

Next when i plot the points this size is not respected.

**Comment by ArthurMcTool** [comment]
I have the exact same issue. My resolution is 1920x1080 and that's as high as I can go. Any help would be appreciated..
